### ISSUE TITLE
Resolve licensing issues with school logo

### ISSUE THREAD

**Issue by cauvmou** [HTL3R-Typst/htl3r-da#5]
Get confirmation from HTL Rennweg that the template is allowed to use the school logo. If this is not possible then include the logo externally.

**Comment by cauvmou** [comment]
Wir haben grünes Licht von der Schule fürs Logo bekommen. Gibt es noch Punkte die hier adressiert werden müssen?

**Comment by kre9** [comment]
nah we ballin :muscle:
